import Head from 'next/head'
import { Box, Flex, Heading, Text, Link } from '@chakra-ui/react'
import Image from 'next/image'

export default function Home() {
	return (
		<Box>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Flex
				direction='column'
				alignItems='center'
				justifyContent='center'
				h='100vh'
				bg='gray.100'
			>
				<Text fontSize='lg' mb={6}>
					_______Get started by editing <code>pages/index.tsx</code>
				</Text>
			</Flex>

			<Box as='footer' textAlign='center' p={4}>
				<Link
					href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
					target='_blank'
					rel='noopener noreferrer'
				>
					Powered by{' '}
					<Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
				</Link>
			</Box>
		</Box>
	)
}
